---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: truecharts-helm-oci
  namespace: argocd
stringData:
  url: oci.trueforge.org/truecharts
  name: truecharts
  type: helm
  enableOCI: "true"
