---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ygege
  namespace: argocd
spec:
  project: default
  destination:
    namespace: dls
    name: in-cluster
  source:
    source:
    repoURL: https://github.com/nmaupu-org/auto-home.git
    targetRevision: master
    path: k8s/argocd/nas/jsonnet/ygege
    plugin:
      name: custom-jsonnet
      parameters:
        - name: values
          string: >-
            image:
              tag: sha256:0437f3c86c8306a7957b216202afc5b32c289c8f859c23836b01ca668fcd4be3
              tagMode: digest
            pvc:
              sessions:
                size: 1Gi
                storageClass: openebs-zfs
            ingress:
              host: ygege.knas.home.fossar.net
              certManager:
                certificateIssuer: google-dns-issuer-prod
              extraAnnotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
            container:
              resources:
                requests:
                  cpu: 50m
                  memory: 16Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
