---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ygege-sessions
  namespace: dls
spec:
  storageClassName: openebs-zfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
