---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ygege
  namespace: dls
spec:
  encryptedData:
    config.json: AgCzPKfYfCGiuXiYxGQD0KzCErXHnVDmhdYeZQL4ZZd3kN42QWRCWZe1OHJ3p9E/Iqs+WTYFrcnHZO9kFF+RkzZU6+HZfVFLok6BUpWFtWoTixXJUABHM9GdPwCWTGia15eDWolYh0hIJiVMQJEhhUP0GveGjodrOq3aFz6+a4LhElExD+yDjMz/hFP7krID7R6azuj1yqEcyrpfqljzIYM4be5qf2l+eKCURCCthV0yKymiQJvOkNUO0Hbf/+AAAgCx9Y2A59oVioUsUTpUZWEALhgEKGFhElr/WHMm7ktvILnQDRZH3ovJBy02Tkp7s096ASZAac9T4U+IeiQJYY3bICJP4Gqh2d/8sPWg4tqpVH+d2+nsKLohSMOLruGYja18LIjWa81R0+DKLxS00zaN7DspaHCOgq5ZhjlcNK8E5vesDr3Dd7QvPcee14toWN4h4vpSVTIhLkG185qyIH0q07cVQLm4KiOGMAlm5Vk/xp6q5ab7gtrtG19mu4bnHlNPYbCjTVonfGEXLuFYAQwLY8bFX0EmPznJJroezN1atW4GLi6Nwc9fqccLyj+ndFE49fkb5IqZmn9tPZ2JqhG4qdbZopKSd1O1FtilRpv8GPYX8RCdZ5EIXtF3o1UmY1m7cka8KwsrtUye+R7ppzQG7UPz623cZRsFwyeYi7eu/MrbA0tZ6W8ZM9VftGTWqpIqGIyswZr9Rt0DB0iAV9DdYY0FIrYwGktAcFNZA0mos5gCifTkHoLnf7qDgoJ2BbZKespbreK4qEdeCWdu+5V7X6TqC1TrEhbtSHHruWsdHxCNLOzS6WmZaY2CgtAfvuGx6I2rNSMkLoMMRRV6BRJll7iigWQSVYfIem3uI08/Aybz8J2dCw==
  template:
    metadata:
      name: ygege
      namespace: dls
