---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cocktails-data
  namespace: cocktails
  annotations:
    # Reloader annotation - tells reloader to watch this ConfigMap
    reloader.stakater.com/match: "true"
data:
  cocktails.yaml: |
    cocktails:
    - name: Smoke On The Cynar
      category:
        en: Custom
        fr: Créations
      image: ./images/smoke-on-the-cynar.jpg
      ingredients:
      - name:
          en: Mezcal
        qty: 40
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 25
      - name:
          en: Agave Syrup
          fr: Sirop d'agave
        qty: 10
      - name:
          en: Cynar
        qty: 20
      - name:
          en: Orange Bitters
          fr: Bitter Orange
        qty: 1 dash
    - name: Mexican Dream
      category:
        en: Creation
        fr: Créations
      image: ./images/mexican-dream.jpg
      ingredients:
      - name:
          en: Tequila
        qty: 30
      - name:
          en: Mezcal
        qty: 20
      - name:
          en: KWE
        qty: 20
      - name:
          en: Ginger Beer
        qty: 100
    - name: Between the sheets
      category:
        en: Rum
        fr: Rhum
      image: ./images/between-the-sheets.jpg
      ingredients:
      - name:
          en: White Rum
          fr: Rhum blanc
        qty: 30
      - name:
          en: Cognac
        qty: 30
      - name:
          en: Triple Sec
        qty: 30
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 20
    - name: Don Beachcomber
      category:
        en: Rum
        fr: Rhum
      image: ./images/don-beachcomber.jpg
      ingredients:
      - name:
          en: White Rum
          fr: Rhum blanc
        qty: 45
      - name:
          en: Triple Sec
        qty: 20
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 15
      - name:
          en: Maraschino
          fr: Marasquin
        qty: 5
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 5
    - name: Basil Smash
      image: ./images/basil-smash.jpg
      ingredients:
      - name:
          en: Gin
        qty: 45
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 20
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 15
      - name:
          en: Green Basil
          fr: Basilic vert
        qty: 15 leaves
    - name: Jasmine
      image: ./images/jasmine.jpg
      ingredients:
      - name:
          en: Gin
        qty: 50
      - name:
          en: Campari
        qty: 10
      - name:
          en: Triple Sec
        qty: 10
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 5
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 2 drops
    - name: Casino
      image: ./images/casino.jpg
      ingredients:
      - name:
          en: Gin
        qty: 40
      - name:
          en: Maraschino
          fr: Marasquin
        qty: 10
      - name:
          en: Orange Bitters
          fr: Bitter Orange
        qty: 2
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 10
    - name: Manhattan Island
      image: ./images/manhattan-island.jpg
      ingredients:
      - name:
          en: Cognac
        qty: 60
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Maraschino
          fr: Marasquin
        qty: 5
      - name:
          en: Angostura
        qty: 3 dashes
    - name: Naked & Famous
      category:
        en: Miscs
        fr: Divers
      image: ./images/naked-and-famous.jpg
      ingredients:
      - name:
          en: Mezcal
        qty: 22.5
      - name:
          en: Yellow Chartreuse
          fr: Chartreuse jaune
        qty: 22.5
      - name:
          en: Aperol
        qty: 22.5
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 22.5
    - name: Oriental
      category:
        en: Whisky
      image: ./images/oriental.jpg
      ingredients:
      - name:
          en: Rye Whiskey
          fr: Whiskey de seigle
        qty: 45
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 22.5
      - name:
          en: Triple Sec
        qty: 22.5
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 15
    - name: Whiskey Smash
      category:
        en: Whisky
      image: ./images/whiskey-smash.jpg
      ingredients:
      - name:
          en: Bourbon
        qty: 45
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 25
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 25
      - name:
          en: Mint
          fr: Menthe
        qty: 3 leaves
    - name: Boulevardier
      category:
        en: Whisky
      image: ./images/boulevardier.jpg
      ingredients:
      - name:
          en: Bourbon
        qty: 45
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Campari
        qty: 30
    - name: Highlander
      category:
        en: Whisky
      image: ./images/highlander.jpg
      ingredients:
      - name:
          en: Scotch Whisky
          fr: Whisky écossais
        qty: 60
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Orange Bitters
          fr: Bitter Orange
        qty: 1 dash
    - name: Manhattan
      category:
        en: Whisky
      image: ./images/manhattan.jpg
      ingredients:
      - name:
          en: Bourbon
        qty: 50
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 25
      - name:
          en: Angostura
        qty: 1 dash
    - name: Margarita
      image: ./images/margarita.jpg
      ingredients:
      - name:
          en: Tequila
        qty: 50
      - name:
          en: Triple Sec
        qty: 20
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 20
    - name: Martinez
      category:
        en: Gin
      image: ./images/martinez.jpg
      ingredients:
      - name:
          en: Gin
        qty: 45
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 45
      - name:
          en: Maraschino
          fr: Marasquin
        qty: 1 bar spoon
      - name:
          en: Orange Bitters
          fr: Bitter Orange
        qty: 2
    - name: Mezcal Negroni
      category:
        en: Americanos
      image: ./images/mezcal-negroni.jpg
      ingredients:
      - name:
          en: Mezcal
        qty: 30
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Campari
        qty: 30
    - name: Negroni
      category:
        en: Americanos
      image: ./images/negroni.jpg
      ingredients:
      - name:
          en: Gin
        qty: 30
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Campari
        qty: 30
    - name: Negroni Sbagliato
      category:
        en: Americanos
      image: ./images/negroni-sbagliato.jpg
      ingredients:
      - name:
          en: Prosecco
        qty: 60
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Campari
        qty: 30
    - name: Suffering Bastard
      image: ./images/suffering-bastard.jpg
      ingredients:
      - name:
          en: Gin
        qty: 30
      - name:
          en: Cognac
        qty: 30
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 15
      - name:
          en: Angostura
        qty: 2 dashes
      - name:
          en: Ginger Beer
        qty: Top Up
    - name: Moscow Mule
      image: ./images/moscow-mule.jpg
      ingredients:
      - name:
          en: Vodka
        qty: 45
      - name:
          en: Ginger Beer
        qty: 120
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 10
    - name: Balalaika
      image: ./images/balalaika.jpg
      ingredients:
      - name:
          en: Vodka
        qty: 35
      - name:
          en: Triple Sec
        qty: 25
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 15
      - name:
          en: Water
          fr: Eau
        qty: 10
    - name: Bee's Knees
      image: ./images/bees-knees.jpg
      ingredients:
      - name:
          en: Gin
        qty: 55
      - name:
          en: Honey Syrup
          fr: Sirop de miel
        qty: 2 teaspoon
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 22.5
      - name:
          en: Orange Juice
          fr: Jus d'orange
        qty: 22.5
    - name: Paloma
      image: ./images/paloma.jpg
      ingredients:
      - name:
          en: Tequila
        qty: 50
      - name:
          en: Grapefruit Soda
          fr: Soda pamplemousse
        qty: 100
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 5
      - name:
          en: Salt
          fr: Sel
        qty: A pinch
    - name: Americano
      category:
        en: Americanos
      image: ./images/americano.jpg
      ingredients:
      - name:
          en: Campari
        qty: 30
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Club Soda
          fr: Eau gazeuse
        qty: Spash
    - name: Whiskey sour
      category:
        en: Whisky
      image: ./images/whiskey-sour.jpg
      ingredients:
      - name:
          en: Bourbon
        qty: 50
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 20
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 20
    - name: Aperol Spritz
      category:
        en: Miscs
        fr: Divers
      image: ./images/aperol-spritz.jpg
      ingredients:
      - name:
          en: Prosecco
        qty: 100
      - name:
          en: Aperol
        qty: 50
      - name:
          en: Angostura
        qty: 2 dashes
    - name: Caipirihna
      image: ./images/caipirihna.jpg
      ingredients:
      - name:
          en: Cachaça
        qty: 60
      - name:
          en: Lime
          fr: Citron vert
        qty: 1
      - name:
          en: Sugar
          fr: Sucre
        qty: 4 teaspoons
    - name: Celtic Margarita
      category:
        en: Whisky
      image: ./images/celtic-margarita.jpg
      ingredients:
      - name:
          en: Scotch Whisky
          fr: Whisky écossais
        qty: 50
      - name:
          en: Triple Sec
        qty: 20
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 20
    - name: Daiquiri
      category:
        en: Rum
        fr: Rhum
      image: ./images/daiquiri.jpg
      ingredients:
      - name:
          en: White Rum
          fr: Rhum blanc
        qty: 50
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 20
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 20
    - name: Garibaldi
      category:
        en: Americanos
      image: ./images/garibaldi.jpg
      ingredients:
      - name:
          en: Campari
        qty: 45
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 5
      - name:
          en: Orange Juice
          fr: Jus d'orange
        qty: On Top
    - name: Gimlet
      image: ./images/gimlet.jpg
      ingredients:
      - name:
          en: Gin
        qty: 50
      - name:
          en: Lime Juice
          fr: Jus de citron vert
        qty: 25
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 15
    - name: Negroski
      image: ./images/negroski.jpg
      ingredients:
      - name:
          en: Vodka
        qty: 35
      - name:
          en: Red Vermouth
          fr: Vermouth rouge
        qty: 30
      - name:
          en: Campari
        qty: 25
    - name: Old Fashioned
      category:
        en: Whisky
      image: ./images/old-fashioned.jpg
      ingredients:
      - name:
          en: Bourbon
        qty: 45
      - name:
          en: Sugar
          fr: Sucre
        qty: 1 cube
      - name:
          en: Angostura
        qty: 2 dashes
      - name:
          en: Water
          fr: Eau
        qty: 1 splash
    - name: Pink Gin
      image: ./images/pink-gin.jpg
      ingredients:
      - name:
          en: Gin
        qty: 60
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 5
      - name:
          en: Angostura
        qty: 4 dashes
    - name: Sidecar
      image: ./images/sidecar.jpg
      ingredients:
      - name:
          en: Cognac
        qty: 50
      - name:
          en: Triple Sec
        qty: 20
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 20
    - name: Aviation
      image: ./images/aviation.jpg
      ingredients:
      - name:
          en: Gin
        qty: 45
      - name:
          en: Maraschino
          fr: Marasquin
        qty: 15
      - name:
          en: Violet Liqueur
          fr: Liqueur de Violette
        qty: 1 Bar Spoon
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 15
    - name: French 75
      image: ./images/french-75.jpg
      ingredients:
      - name:
          en: Prosecco
        qty: 60
      - name:
          en: Gin
        qty: 30
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 15
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 15
    - name: French 125
      image: ./images/french-125.jpg
      ingredients:
      - name:
          en: Prosecco
        qty: 60
      - name:
          en: Cognac
        qty: 30
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 15
      - name:
          en: Simple Syrup
          fr: Sirop simple
        qty: 15
    - name: Kamikaze
      image: ./images/kamikaze.jpg
      ingredients:
      - name:
          en: Vodka
        qty: 30
      - name:
          en: Triple Sec
        qty: 30
      - name:
          en: Lemon Juice
          fr: Jus de citron
        qty: 30
