apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ygege-secret
spec:
  encryptedData:
    config.json: AgDOzmyOUGOnXnDAhucA89KXMbgLizP9p3Z/Tq0S4qy7/wWsvUzgPePp9ZsUZhfsWT0oSfsfWoUOsZ4k2ki3C4RxmNPN43XloXjNi6Yo2F8XfMr3dPaqFkgdWp/2vTRyDX9uaJkgeL3nAA56c2nUXB1oelcm9x5bonMU4h5JfWqdwNRKjxYjuQTVqxLCzjHOWiKZILj5DEwIAHBgewNw/KLuTgZzalwUEr1FQzdVoEEzoy+zBf+jmPTcZnMhYpEPnIdIfIkMhklz9T/jNXyr71KYUrQK9UBhxEQqjetV2CUu8XtiG6HpKGf5o8TUz5ykuO8bEot9Od0YgjXd41zCYhR11aViI704C7JBpPD5yzij4oIQ3fhrFUd9KVOdI9a0PsdghH9LrEWqigsBOoXVUrVGltt71rzNqpSRkelfMaMVCgTk8yzECEiR1CpxGvtaU/HLMwnCZiW8QXVXCMDNcw8GKVCVA5Q9h70QjGfBieaaqOvaAb99rbu8/KJYYS0QvPno/jhRy9N9ACL5PGmBjN4CB5VWXzEG7sUEr+sp55BEJsPSbv4vWiNIr26PxBYBPA69GzqIwZeRCwKLhcCBvV6y5SRuBZUdSz4Cin0IyWZbshqh6LciYR1pI8q2m5fjxHKWJnJoTKj93rW8Wx0nIzoBVAzpvGQYavE9pgDsQ/5NmHTUyR6gocIZvgmmTZH5LXa0J3kQU8JbUrIC11HNWeCQZBLjVrfw8XwJ8aePBXBGtrYhvlKzmzJaEMQxXB5cIz2LcWw/jkFGDMbvzGGhsAu6B7w+90rM35ul1nH4whYDnhfv3gpGmMMzJR3dP+mORFIUQAqKRnm1Fhyl340ZETgFDJwVNYrkoaSlDDd3ou9KBr48o4Tg9A==
  template:
    metadata:
      name: ygege-secret
      namespace: dls
